"""Acceptance tests for the argparse-to-boutiques pipeline.

These are end-to-end tests: they run the real ``run_argdump.py`` -> ``styx
build --backend boutiques`` pipeline that the GitHub Action wraps, then
validate the result with the Boutiques reference validator (``bosh``).

They are integration tests and need external tools. Configure via env vars,
which default to typical locations:

    RUN_ARGDUMP   path to run_argdump.py            (default: ../scripts/run_argdump.py)
    STYX          styx CLI binary                   (default: npx ... styx)
    BOSH          bosh validator binary             (default: bosh)

The whole module skips if styx or bosh are unavailable, so a unit-test-only
run is unaffected.

Findings these tests encode (determined empirically against styx 0.0.1 /
boutiques 0.5.33):

  * styx emits ``schema-version: "0.5+styx"`` and never emits
    ``tool-version``; ``description`` is only present if the source parser
    set one. All three must be normalized for the output to be valid
    *vanilla* Boutiques. ``normalize_descriptor`` below mirrors the
    post-processing the Action should apply.
  * Even after normalization, three argparse constructs produce invalid
    Boutiques and are marked xfail: ``action="count"`` (-vvv),
    ``nargs="?"``, and subparsers/subcommands.
  * A parser that does not set ``prog=`` leaks the runner's name
    (run_argdump.py) into the descriptor ``name``/``command-line``.
"""
import json
import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent

# TODO: maybe automate finding the correct path where scripts/ is instead of HERE.parent.parent
RUN_ARGDUMP = Path(
    os.environ.get("RUN_ARGDUMP", HERE.parent.parent / "scripts" / "run_argdump.py")
)
# STYX may be a multi-token command (e.g. "npx -y --package @styx-api/cli styx").
STYX = os.environ.get(
    "STYX", "npx -y --package @styx-api/cli styx"
)
BOSH = os.environ.get("BOSH", "bosh")

# Fixture parsers live next to this test file.
FIXTURE_DIR = HERE
FIXTURE_MODULE = "sample_parsers"


def _tool_available() -> bool:
    bosh = shutil.which(BOSH.split()[0])
    styx_head = STYX.split()[0]
    styx = shutil.which(styx_head) or Path(styx_head).exists()
    return bool(bosh and styx and RUN_ARGDUMP.exists())


pytestmark = pytest.mark.skipif(
    not _tool_available(),
    reason="acceptance tests need run_argdump.py, styx and bosh available",
)


# --------------------------------------------------------------------------- #
# Pipeline helpers
# --------------------------------------------------------------------------- #
def run_pipeline(func_name: str, tmp_path: Path) -> Path:
    """Run argdump + styx for one parser builder; return the descriptor path."""
    location = f"{FIXTURE_MODULE}:{func_name}"
    argdump_json = tmp_path / "argdump.json"
    styx_out = tmp_path / "styx-out"

    env = {**os.environ, "PYTHONPATH": str(FIXTURE_DIR)}

    # stage 1: argparse -> argdump JSON
    subprocess.run(
        [sys.executable, str(RUN_ARGDUMP), "--output", str(argdump_json), location],
        check=True, env=env, capture_output=True, text=True,
    )

    # stage 2: argdump JSON -> Boutiques (mirrors the Action's styx call)
    subprocess.run(
        [*shlex.split(STYX), "build", str(argdump_json),
         "--out", str(styx_out), "--backend", "boutiques"],
        check=True, capture_output=True, text=True,
    )

    descriptors = list(styx_out.rglob("descriptor.json"))
    assert descriptors, f"styx produced no descriptor.json under {styx_out}"
    return descriptors[0]


def normalize_descriptor(path: Path) -> Path:
    """Apply the post-processing needed for *vanilla* Boutiques validity.

    This represents work the Action should do after styx but currently does
    not: pin schema-version to 0.5 and supply the required description /
    tool-version when styx omitted them.
    """
    d = json.loads(path.read_text())
    d["schema-version"] = "0.5"
    d.setdefault("description", "Generated by argparse-to-boutiques.")
    d.setdefault("tool-version", "0.0.0")
    path.write_text(json.dumps(d))
    return path


def is_valid_boutiques(path: Path) -> bool:
    result = subprocess.run(
        [*shlex.split(BOSH), "validate", str(path)],
        capture_output=True, text=True,
    )
    return result.returncode == 0


# --------------------------------------------------------------------------- #
# Happy path: pipeline runs and (after normalization) yields valid Boutiques
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize(
    "func", ["simple", "append_action", "mutually_exclusive", "filetype_arg"]
)
def test_pipeline_yields_valid_boutiques(func, tmp_path):
    descriptor = run_pipeline(func, tmp_path)
    assert descriptor.is_file()
    normalize_descriptor(descriptor)
    assert is_valid_boutiques(descriptor)


def test_raw_styx_output_is_not_vanilla_boutiques(tmp_path):
    """Document that styx output needs normalization (schema-version etc.)."""
    descriptor = run_pipeline("simple", tmp_path)
    assert not is_valid_boutiques(descriptor)  # 0.5+styx, no tool-version
    raw = json.loads(descriptor.read_text())
    assert raw["schema-version"] == "0.5+styx"
    assert "tool-version" not in raw


# --------------------------------------------------------------------------- #
# Known limitations: invalid even after normalization (xfail = documented)
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("func", ["count_action", "nargs_optional", "subcommands"])
def test_unsupported_constructs_do_not_validate(func, tmp_path):
    descriptor = run_pipeline(func, tmp_path)
    normalize_descriptor(descriptor)
    # These currently produce invalid Boutiques; assert that explicitly so a
    # future styx fix that makes them valid will flip this test and prompt
    # a review.
    assert not is_valid_boutiques(descriptor), (
        f"{func} now validates - styx may have gained support; update tests."
    )


# --------------------------------------------------------------------------- #
# prog-name leak
# --------------------------------------------------------------------------- #
def test_prog_set_is_used_as_name(tmp_path):
    descriptor = run_pipeline("simple", tmp_path)  # sets prog="simple"
    assert json.loads(descriptor.read_text())["name"] == "simple"


def test_missing_prog_leaks_runner_name(tmp_path):
    descriptor = run_pipeline("no_prog", tmp_path)  # no prog set
    name = json.loads(descriptor.read_text())["name"]
    # Documents the leak: without prog=, the descriptor is named after the
    # runner script rather than the tool.
    assert name == RUN_ARGDUMP.name


# --------------------------------------------------------------------------- #
# Error handling: malformed parser-location must fail loudly (non-zero exit)
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize(
    "location",
    [
        "no_colon_here",                       # missing ":"
        "module_does_not_exist_xyz:func",      # bad module
        f"{FIXTURE_MODULE}:does_not_exist",    # bad function
        f"{FIXTURE_MODULE}:not_a_parser",      # returns non-parser
    ],
)
def test_bad_location_exits_nonzero(location, tmp_path):
    env = {**os.environ, "PYTHONPATH": str(FIXTURE_DIR)}
    result = subprocess.run(
        [sys.executable, str(RUN_ARGDUMP), "--output",
         str(tmp_path / "out.json"), location],
        env=env, capture_output=True, text=True,
    )
    assert result.returncode != 0
